export const data = [
  {
    image: require("../src/assets/1.png"),
    name: "Steve Richmond",
    message: "Yes, let's do it!",
    online: true,
    read: false,
  },
  {
    image: require("../src/assets/2.png"),
    name: "Cassian Mcdermott",
    message: "How are you doing?",
    online: false,
    read: false,
  },
  {
    image: require("../src/assets/3.png"),
    name: "Chance Zhang",
    message: "Liked your message",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/4.png"),
    name: "Lleyton Workman",
    message: "Lol, ew.",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/5.png"),
    name: "Molly Morton",
    message: "Mad Max!",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/6.png"),
    name: "Winnie Greenwood",
    message: "Mandy told me to..",
    online: false,
    read: false,
  },
  {
    image: require("../src/assets/7.png"),
    name: "Brendon Andrew",
    message: "I mean we definitely could",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/8.png"),
    name: "Norman Hutchings",
    message: "Have you ever tried surfing?",
    online: true,
    read: false,
  },
  {
    image: require("../src/assets/9.png"),
    name: "Maciej Miranda",
    message: "Danny is incredibly funny!!",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/10.png"),
    name: "Zara Osborne",
    message: "How are you doing?",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/11.png"),
    name: "Rui Black",
    message: "Are we able to delivery in time?",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/12.png"),
    name: "Yazmin Pate",
    message: "For sure! Consistency is key.",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/13.png"),
    name: "Kristina Martins",
    message: "Like Casey Neistat?",
    online: true,
    read: false,
  },
  {
    image: require("../src/assets/14.png"),
    name: "Ryan Buckner",
    message: "At this point, I am not suprised",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/15.png"),
    name: "Amna Partridge",
    message: "Tomorrow, we are ✈️✈️",
    online: false,
    read: false,
  },
  {
    image: require("../src/assets/16.png"),
    name: "Paris Kirby",
    message: "I am running out of ideas..",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/17.png"),
    name: "Darrel Glover",
    message: "You sent a voice message",
    online: false,
    read: true,
  },
  {
    image: require("../src/assets/18.png"),
    name: "Peter Singh",
    message: "Cold brew — for sure!",
    online: false,
    read: false,
  },
  {
    image: require("../src/assets/19.png"),
    name: "Tobi Pugh",
    message: "Liked a message",
    online: true,
    read: true,
  },
  {
    image: require("../src/assets/20.png"),
    name: "Drew Bean",
    message: "Replied to your story: 💯",
    online: false,
    read: true,
  },
];
